spring:
  jpa:
#    show-sql: true

  cache: # spring data cache 설정
    type: redis
    redis: # redis의 기본값은 localhost:6379입니다. redis-server를 설치해야 사용할 수 있습니다.
      host: ${REDIS_HOST_URL}
      port: ${REDIS_PORT}
      cache-null-values: true # null 캐싱 여부

open-api:
    url: # 경기도 URL
    secret-key: # Secret-key 입력

springdoc:
  packages-to-scan: com.example.socialmediafeed.domain # 스캔할 패키지의 목록을 설정. 콤마로 구분된 패키지 이름 목록을 제공하여 특정 패키지만 스캔하도록 설정할 수 있습니다.
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  enable-spring-security: false #  spring-security 지원을 활성화하거나 비활성화하는 데 사용됩니다.
  # false로 설정하면, Springdoc OpenAPI는 Spring Security 설정을 무시하고 모든 API 엔드포인트를 문서화합니다.
  # Springdoc OpenAPI가 Spring Security를 무시한다는 것이지, Spring Security 자체가 비활성화된다는 것은 아닙니다.
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

jwt:
  header: Authorization
  secret: bG9jYXRpb24tYmFzZWQtZ291cm1ldC1yZWNvbW1lbmRhdGlvbi1wcm9qZWN0
  expiration:
    access : 86400
    refresh : 604800